### ISSUE TITLE
Duplicate word "to" in solution of quiz of Lesson 2 Concept 8

### ISSUE THREAD

**Issue by yemikifouly** [OpenMined/courses#136]
"Correct - sometimes satisfying privacy is about forcing companies to **to** share or delete your data in a specific way or at a specific time."

_Originally posted by @abulyomon in https://github.com/OpenMined/courses/discussions/107_

The correct sentence should be: "Correct - sometimes satisfying privacy is about forcing companies to share or delete your data in a specific way or at a specific time."

**Comment by em-blue** [comment]
fixed
