### ISSUE TITLE
Broken link in Lesson 2: Feedback mechanisms & information flows.

### ISSUE THREAD

**Issue by yemikifouly** [OpenMined/courses#191]
## Description
The link titled: "Exposed the tricks sellers use to post fake reviews on Amazon" is not working.

## How to Reproduce
1. Go to [the concept](https://courses.openmined.org/courses/our-privacy-opportunity/1f34d3a8-2fa1-4a1e-9ef1-eaaf9dddd617/04cea8cb-aa0d-4e95-bbb5-a20d768e9546).
2. In the additional resources, click on the link titled "Exposed the tricks sellers use to post fake reviews on Amazon".
3. 404 page appears.

Mentioned in [this post](https://github.com/OpenMined/courses/discussions/188#discussion-1734525).

**Comment by yemikifouly** [comment]
@iamtrask Can you help with this?

**Comment by em-blue** [comment]
Fixed it! @yemikifouly
