### ISSUE TITLE
Include Conda Environment Setup Instructions

### ISSUE THREAD

**Issue by leriomaggio** [OpenMined/courses#309]
## Description
Despite `conda` is the recommended package manager, dependencies for the course are available via `pip` and `requirements.txt`.

I thought that *also* having a Conda Environment file could've been handy - also to avoid any issue in setting up all the packages and corresponding versions.

## Are you interested in working on this improvement yourself?
- Yes, I am. - actually I already did 😬 

## Additional Context
Add any other context or screenshots.

**Comment by mcleonard** [comment]
Thanks for this! I left one little comment on the PR review

**Comment by leriomaggio** [comment]
Hi @mcleonard thanks for taking the time to review the PR.. unfortunately I cannot find the comment you're mentioning. as a matter of fact I can't see any review on the PR? 🤔

**Comment by mcleonard** [comment]
Oh geez, I had to click an extra button 🤦 . You should see it now
