### ISSUE TITLE
Lesson 2: Conflict, Political Science & Information Flows - Reference Video Missing

### ISSUE THREAD

**Issue by mcleonard** [OpenMined/courses#98]
From https://github.com/OpenMined/courses/discussions/92

Near the end of the video, Andrew referenced a segment video discussing the conflict between India and Pakistan, but such a segment is missed. I guess is related to a glitch in editing.

**Comment by iamtrask** [comment]
Fixed video is uploading

**Comment by iamtrask** [comment]
Fixed and replaced in course platform.
